name: logging_tree tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Print Python version
      run: python3 --version
    - name: Test
      run: python3 -m unittest discover -v logging_tree
